### ISSUE TITLE
Connect to localhost:3000 from another computer 

### ISSUE THREAD

**Issue by Deca** [xdk2mam/xdk2mam-dashboard#54]
Hi,

I'm trying to view and use the dashboard from other pc and devices in the same network and not only from localhost, I see that the dashboard is using the expressjs web framework but I don't have much experience on it
I tried to bind the app.listen method to "all ip's" 0.0.0.0 and the dashboard is visible but I'm not able to create a new dataset, do you have any idea how to use fully the dashboard on a LAN?

**Comment by andyesp** [comment]
Hi! Both computers must be connected to the same network. And then you can access the web app entering your ip + port 3000. E.g: `http//192.168.0.51:3000`.
